Update issue 109 Initial go at 'sift' tool

diff --git a/sift b/sift
--- a/sift
+++ b/sift
@@ -1,62 +1,263 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# This program is part of Aspersa (http://code.google.com/p/aspersa/)
 
-# TODO: look at issue 11940 note for example of good summary of status
+# ########################################################################
+# This script browses the files created by the collect tool.
+#
+# Author: Baron Schwartz
+# ########################################################################
 
-echo "Samples of disk fill"
-awk '/^\// { print $1 " " $3 }' $1-df | sort | uniq -c
+# Show current help and settings
+print_help() {
+   cat <<-HELP
+   You can control this program with key presses.
+                  ---  COMMANDS  ---
+      1  Default action: summarize files
+      *  View all the files in less
+                  --- NAVIGATION ---
+      j  Select the next timestamp
+      k  Select the previous timestamp
+      q  Quit the program
+	HELP
+}
 
-echo
-for dev in $(head $1-df | awk '/^\// { print $1 }' | sort -u); do
-   echo "Disk statistics for ${dev}"
-   grep ${dev} $1-diskstats
-done
+usage() {
+   if [ "${OPT_ERR}" ]; then
+      echo "${OPT_ERR}"
+   fi
+   cat <<-USAGE
+Usage: $0 [OPTIONS] [FILE|PREFIX|DIRECTORY]
+   $0 helps you browse the files written by the collect tool.
+   If you specify a FILE or PREFIX, it browses only files with that prefix.  If you
+   specify a DIRECTORY, then it browses all files within that directory.
+	USAGE
+   exit 1
+}
 
-echo
-echo "InnoDB stats"
-grep "Main thread" $1-innodb*
-grep "queries inside" $1-innodb*
-grep -i -A1 "pending" $1-innodb*
+# The main code that runs by default.  Arguments are the command-line options.
+main() {
 
-echo "InnoDB semaphores: threads are waiting at..."
-awk '
-   /has waited at/ { print $6 " " $7 " " $8 }
-   ' $1-innodb* | sort | uniq -c | sort -rn
-echo "InnoDB semaphores: threads are waiting on..."
-awk '
-   /^[XS]-lock on.*latch/ { print }
-   ' $1-innodb* | sort | uniq -c | sort -rn
-echo "InnoDB semaphores: each thread is blocking how many other threads?"
-awk '
-   /a [^ ]*er .thread id/ { print substr($5, 1, index($5, ")") - 1)}
-   ' $1-innodb* | sort | uniq -c | sort -rn | awk '{printf "%18d blocks %3d others\n", $2, $1}'
+   # If the programs we need don't exist, try to get them.
+   for prog in align diskstats pmp mext; do
+      if which $prog >/dev/null 2>&1 ; then
+         eval "PR_$prog"="$(which $prog)"
+      elif test -f $prog && test -x $prog; then
+         eval "PR_$prog"="./$prog"
+      else
+         echo "Fetching $prog"
+         curl http://aspersa.googlecode.com/svn/trunk/$prog > $prog && chmod +x $prog
+         eval "PR_$prog"="./$prog"
+      fi
+   done
 
-exit
+   # If there's a command-line arg, figure out if it's a file, directory, or
+   # prefix.  The outcome of this block of code should be that BASEDIR is the
+   # directory where the files live, without a trailing slash; and PREFIX is
+   # either empty or a timestamp, such as "2011_02_08_16_58_07".
+   ARG="${1:-.}"
+   if [ -d "${ARG}" ]; then
+      BASEDIR="$(echo "${ARG}" | sed -e 's!/$!!')"
+   elif [ -f "${ARG}" -o -f "${ARG}-df" -o -f "${ARG}df" ]; then
+      BASEDIR="$(dirname "${ARG}")"
+      PREFIX="$(echo "${ARG}" | sed -e 's/-[^-]*$//' -e 's!^.*/!!')"
+   else
+      echo "Error: ${ARG} doesn't look like a directory, file, or file prefix"
+      exit 1
+   fi
 
-# TODO: do both in one pass with associative arrays
-echo
-echo "Source of connections to MySQL"
-awk '/:3306/ { print substr($5, 0, index($5, ":") - 1) }' $1-netstat | sort | uniq -c | sort -rn
-echo
-echo "Status of connections to MySQL"
-awk '/:3306/ { print $6 }' $1-netstat | sort | uniq -c | sort -rn
+   # We need to generate a list of timestamps, and ask the user to choose one if
+   # there is no PREFIX yet.  NOTE: we rely on the "-df" files here.
+   ls "${BASEDIR}" | grep -- '-df$' | cut -d- -f1 | sort > /tmp/aspersa.sift-prefixes
+   if [ -z "${PREFIX}" ]; then
+      echo
+      i=0
+      cat /tmp/aspersa.sift-prefixes | while read line; do
+         i=$(($i + 1))
+         echo -n "  $line"
+         if [ "${i}" = "3" ]; then
+            echo
+            i=0
+         fi
+      done
+      # We might have ended mid-line or we might have printed a newline; print a
+      # newline if required to end the list of timestamp prefixes.
+      awk 'BEGIN { i = 0 } { i++ } END { if ( i % 3 != 0 ) { print "" } }' /tmp/aspersa.sift-prefixes
+      echo
+      while [ "$(grep -c "${PREFIX}" /tmp/aspersa.sift-prefixes)" -ne 1 ]; do
+         read -e -i "$(tail -1 /tmp/aspersa.sift-prefixes)" -p "Select a timestamp from the list: " ARG
+         if [ "$(grep -c "${ARG}" /tmp/aspersa.sift-prefixes)" -eq 1 ]; then
+            PREFIX="$(grep "${ARG}" /tmp/aspersa.sift-prefixes)"
+         fi
+      done
+   fi
 
-for i in 1 2; do
-   echo
-   echo "Users for processlist $i"
-   awk -F: '/^ *User:/{print $2}' $1-processlist$i | sort | uniq -c | sort -rn
-   echo "States for processlist $i"
-   awk -F: '/^ *State:/{print $2}' $1-processlist$i | sort | uniq -c | sort -rn
-   echo "Commands for processlist $i"
-   awk -F: '/^ *Command:/{print $2}' $1-processlist$i | sort | uniq -c | sort -rn
-done
+   KEY=""
+   ACTION="DEFAULT"
+   while [ "${KEY}" != "q" ]; do
 
-echo
-echo "Stacktraces"
+      # Print the current timestamp and action
+      echo "===================== ${PREFIX} ${ACTION} ========================="
 
-awk '
-   BEGIN { s = ""; }
-   /Thread/ { print s; s = ""; }
-   /^\#/ { if (s != "" ) { s = s "," $4} else { s = $4 } }
-   END { print s }' \
-   $1-stacktrace | sort | uniq -c | sort -rn
+      # Take an action based on the current $ACTION
+      case "${ACTION}" in
 
+         # Format a brief report: busiest device's disk stats, CPU stats
+         DEFAULT)
+            echo "--diskstats--"
+            $PR_diskstats -g disk "${BASEDIR}/${PREFIX}-diskstats" \
+               | awk '
+                  /ts/ { header = $0 }
+                  /\d/ {
+                     io = $3 + $6;
+                     if ( io >= mio ) {
+                        mio   = io;
+                        mseen = $0;
+                     }
+                  }
+                  END {
+                     print header;
+                     print mseen;
+                  }'
+            echo "--vmstat--"
+            tail -n 3 "${BASEDIR}/${PREFIX}-vmstat-overall" | $PR_align
+            echo "--innodb--"
+            awk '
+               /queries inside/ {
+                  inside = $0;
+               }
+               /Main thread/ {
+                  main_state = $NF;
+               }
+               /Pending normal/ {
+                  pending_reads += substr($5, 1, length($5) - 1);
+                  pending_reads += substr($NF, 1, length($NF) - 1);
+               }
+               /ibuf aio reads/ {
+                  pending_reads += substr($4, 1, length($4) - 1);
+                  pending_reads += substr($7, 1, length($7) - 1);
+                  pending_reads += $NF;
+               }
+               /Pending flushes/ {
+                  pending_flushes = substr($5, 1, length($5) - 1) + $NF;
+               }
+               /pending preads/ {
+                  pending_reads += $1;
+                  pending_writes += $4;
+               }
+               /pending log writes/ {
+                  pending_writes += $1 + $5;
+               }
+               /Pending reads/ {
+                  pending_reads += $NF;
+               }
+               /Pending writes/ {
+                  pending_writes += substr($4, 1, length($4) - 1);
+                  pending_writes += substr($7, 1, length($7) - 1);
+                  pending_writes += $NF;
+               }
+               /Log sequence number/ {
+                  if ( $NF == 5 ) {
+                     lsn = ($4 * (2^32)) + $5;
+                  }
+                  else {
+                     lsn = $4;
+                  }
+               }
+               /Last checkpoint at/ {
+                  if ( $NF == 5 ) {
+                     chkp = ($4 * (2^32)) + $5;
+                  }
+                  else {
+                     chkp = $4;
+                  }
+               }
+               END {
+                  print "    " inside;
+                  printf "    Main thread: %s, pending reads %d, writes %d, flush %d\n", main_state, pending_reads, pending_writes, pending_flushes;
+                  printf "    Log: lsn = %d, chkp = %d, chkp age = %d\n", lsn, chkp, lsn - chkp;
+               }
+            ' "${BASEDIR}/${PREFIX}-innodbstatus1"
+            echo "    Threads are waiting at:"
+            awk '/has waited at/ { print $6, $7, $8 }' \
+              "${BASEDIR}/${PREFIX}-innodbstatus1" | sort | uniq -c | sort -rn
+            echo "    Threads are waiting on:"
+            awk '/^[XS]-lock on.*latch/ { print }' \
+              "${BASEDIR}/${PREFIX}-innodbstatus1" | sort | uniq -c | sort -rn
+            echo "--processlist--"
+            for word in State Command; do
+               echo "    $word"
+               awk -F: "/^ *$word:/{print \$2}" \
+                  "${BASEDIR}/${PREFIX}-processlist1" \
+                  | sort | uniq -c | sort -rn | head -n 5
+            done
+            echo "--stack traces--"
+            $PR_pmp -l 5 "${BASEDIR}/${PREFIX}-stacktrace" | head -n 5
+            echo "--oprofile--"
+            awk '
+               {
+                  if ( $1 == "samples" ) {
+                     go = 1;
+                  }
+                  if ( go == 1 ) {
+                     print "    " $0;
+                     if ( printed++ == 6 ) {
+                        exit;
+                     }
+                  }
+               } ' "${BASEDIR}/${PREFIX}-opreport"
+            ;;
+
+         VIEW)
+            less ${BASEDIR}/${PREFIX}-*
+            ;;
+
+      esac
+
+      # Capture and handle the interactive key-strokes.
+      KEY=""
+      read -n 1 -s KEY
+      case "${KEY}" in
+         j|k)
+            PREFIX="$(awk "
+               BEGIN {
+                  printed = 0;
+               }
+               {
+                  prev=curr;
+                  curr=\$1;
+                  if ( \"j\" == \"${KEY}\" && prev == \"${PREFIX}\" && curr ~ /./ ) {
+                     print curr;
+                     printed = 1;
+                     exit;
+                  }
+                  if ( \"k\" == \"${KEY}\" && curr == \"${PREFIX}\" && prev ~ /./ ) {
+                     print prev;
+                     printed = 1;
+                     exit;
+                  }
+               }
+               END {
+                  if ( printed == 0 ) {
+                     print \"${PREFIX}\";
+                  }
+               }" /tmp/aspersa.sift-prefixes)"
+            ;;
+         1)
+            ACTION="DEFAULT"
+            ;;
+         '*')
+            ACTION="VIEW"
+            ;;
+         '?')
+            print_help
+            ;;
+      esac
+   done
+
+}
+
+# Execute the program if it was not included from another file.  This makes it
+# possible to include without executing, and thus test.
+if [ $(basename "$0") = "sift" ] || [ $(basename "$0") = "bash" -a "$_" = "$0" ]; then
+    main $@
+fi
